### ISSUE TITLE
Can  not  package the project 

### ISSUE THREAD

**Issue by solderain** [parttimenerd/dead-code-agent#1]
Try to download the project  [dead-code-agent] code  and then exe  mvn package  , but  get the following error msg , 
![image](https://github.com/parttimenerd/dead-code-agent/assets/4144738/15b79186-2b54-4260-ad53-89c12e40e0a3)
![image](https://github.com/parttimenerd/dead-code-agent/assets/4144738/3492f47c-13b7-47a2-907d-3ebb575e70f8)

**Comment by parttimenerd** [comment]
Can you run `mvn` on the command line yourself?

**Comment by solderain** [comment]
Yes , it  works well    run  mvn  on the command line , thks

**Comment by solderain** [comment]
run  mvn on  idea :
![image](https://github.com/parttimenerd/dead-code-agent/assets/4144738/9cfd371a-a283-43c3-a2b0-0995c7200980)
run mvn on terminal :
